# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_title', models.CharField(max_length=50)),
                ('details_url', models.FileField(upload_to='details_pic/')),
                ('details_text', models.TextField(default='')),
                ('details_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glorys_title', models.CharField(max_length=50)),
                ('glorys_url', models.FileField(upload_to='glorys_pic/')),
                ('glorys_text', models.TextField(default='')),
                ('glorys_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='logo_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_index', models.FileField(upload_to='index_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_url', models.FileField(upload_to='news_pic/')),
                ('news_text', models.TextField(default='')),
                ('news_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pic_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_index', models.FileField(upload_to='index_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_title', models.CharField(max_length=50)),
                ('projects_url', models.FileField(upload_to='projects_pic/')),
                ('projects_text', models.TextField(default='')),
                ('projects_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='text_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_index', models.CharField(max_length=1000)),
                ('hq_index', models.FileField(upload_to='index_text/')),
            ],
        ),
        migrations.CreateModel(
            name='video_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_index', models.FileField(upload_to='index_video/')),
            ],
        ),
    ]
