# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_index',
            name='about_index',
            field=models.TextField(default=''),
        ),
    ]
