# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0006_auto_20170714_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.IntegerField(choices=[(0, '海桥快讯'), (1, '行业动态')]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_type',
            field=models.IntegerField(choices=[(0, '公寓住所/酒店'), (1, '商业工程')]),
        ),
    ]
