# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0013_auto_20170716_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='details_url',
            field=models.FileField(default='', upload_to='details_pic/'),
        ),
        migrations.AlterField(
            model_name='glorys',
            name='glorys_url',
            field=models.FileField(default='', upload_to='glorys_pic/'),
        ),
        migrations.AlterField(
            model_name='logo_index',
            name='logo_index',
            field=models.FileField(default='', upload_to='index_logo/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.FileField(default='', upload_to='news_pic/'),
        ),
        migrations.AlterField(
            model_name='pic_index',
            name='pic_index',
            field=models.FileField(default='', upload_to='index_pic/'),
        ),
        migrations.AlterField(
            model_name='text_index',
            name='hq_index',
            field=models.FileField(default='', upload_to='index_text/'),
        ),
        migrations.AlterField(
            model_name='video_index',
            name='video_index',
            field=models.FileField(default='', upload_to='index_video/'),
        ),
    ]
