# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0015_auto_20170716_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='details_text',
            field=models.TextField(default=b'', verbose_name='\u884c\u4e1a\u52a8\u6001\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='details',
            name='details_time',
            field=models.DateField(auto_now=True, verbose_name='\u884c\u4e1a\u52a8\u6001\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='details',
            name='details_title',
            field=models.CharField(max_length=50, verbose_name='\u884c\u4e1a\u52a8\u6001\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='details',
            name='details_url',
            field=models.FileField(default=b'', upload_to=b'details_pic/', verbose_name='\u884c\u4e1a\u52a8\u6001\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='glorys',
            name='glorys_text',
            field=models.TextField(default=b'', verbose_name='\u5956\u9879\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='glorys',
            name='glorys_time',
            field=models.DateField(auto_now=True, verbose_name='\u83b7\u5956\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='glorys',
            name='glorys_title',
            field=models.CharField(max_length=50, verbose_name='\u5956\u9879\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='glorys',
            name='glorys_url',
            field=models.FileField(default=b'', upload_to=b'glorys_pic/', verbose_name='\u5956\u9879\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='logo_index',
            name='logo_index',
            field=models.FileField(default=b'', upload_to=b'index_logo/', verbose_name='\u516c\u53f8logo\u56fe'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(default=b'', verbose_name='\u65b0\u95fb\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_time',
            field=models.DateField(auto_now=True, verbose_name='\u65b0\u95fb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=50, verbose_name='\u65b0\u95fb\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.FileField(default=b'', upload_to=b'news_pic/', verbose_name='\u65b0\u95fb\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='pic_index',
            name='pic_index',
            field=models.FileField(default=b'', upload_to=b'index_pic/', verbose_name='\u9996\u9875\u5927\u56fe'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_text',
            field=models.TextField(default=b'', verbose_name='\u9879\u76ee\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_time',
            field=models.DateField(auto_now=True, verbose_name='\u9879\u76ee\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_title',
            field=models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_type',
            field=models.IntegerField(choices=[(0, '\u516c\u5bd3\u4f4f\u6240/\u9152\u5e97'), (1, '\u5546\u4e1a\u5de5\u7a0b')], verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_url',
            field=models.FileField(default=b'', upload_to=b'projects_pic/', verbose_name='\u9879\u76ee\u5927\u56fe'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_url1',
            field=models.FileField(default=b'', upload_to=b'projects_pic/', verbose_name='\u7ec6\u8282\u5c0f\u56fe1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_url2',
            field=models.FileField(default=b'', upload_to=b'projects_pic/', verbose_name='\u7ec6\u8282\u5c0f\u56fe2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_url3',
            field=models.FileField(default=b'', upload_to=b'projects_pic/', verbose_name='\u7ec6\u8282\u5c0f\u56fe3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_url4',
            field=models.FileField(default=b'', upload_to=b'projects_pic/', verbose_name='\u7ec6\u8282\u5c0f\u56fe4'),
        ),
        migrations.AlterField(
            model_name='text_index',
            name='about_index',
            field=models.TextField(default=b'', verbose_name='\u9996\u9875\u516c\u53f8\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='text_index',
            name='hq_index',
            field=models.FileField(default=b'', upload_to=b'index_text/', verbose_name='\u516c\u53f8\u56fe\u7247\uff08\u5c0f\uff09'),
        ),
        migrations.AlterField(
            model_name='video_index',
            name='video_index',
            field=models.FileField(default=b'', upload_to=b'index_video/', verbose_name='\u9996\u9875\u5ba3\u4f20\u89c6\u9891'),
        ),
    ]
